// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj0xGKdiYR600LqaiKGY_vNxWLP3sGrsc',
    appId: '1:527153013803:web:23f27303f946d4096cb66e',
    messagingSenderId: '527153013803',
    projectId: 'csa-quiz-app',
    authDomain: 'csa-quiz-app.firebaseapp.com',
    storageBucket: 'csa-quiz-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg_mVM4IrLE7BzbISTx-VZZyvr5RoMJJo',
    appId: '1:527153013803:android:bd1e70b3a58925d16cb66e',
    messagingSenderId: '527153013803',
    projectId: 'csa-quiz-app',
    storageBucket: 'csa-quiz-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAYSaqiOHh2FcfYjo4lXqUtfKlRH0lPCw',
    appId: '1:527153013803:ios:d2fa0abcd84700786cb66e',
    messagingSenderId: '527153013803',
    projectId: 'csa-quiz-app',
    storageBucket: 'csa-quiz-app.appspot.com',
    iosClientId: '527153013803-gm5maliv802gse68d79j1efv5ln67su4.apps.googleusercontent.com',
    iosBundleId: 'com.example.csaQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAYSaqiOHh2FcfYjo4lXqUtfKlRH0lPCw',
    appId: '1:527153013803:ios:d2fa0abcd84700786cb66e',
    messagingSenderId: '527153013803',
    projectId: 'csa-quiz-app',
    storageBucket: 'csa-quiz-app.appspot.com',
    iosClientId: '527153013803-gm5maliv802gse68d79j1efv5ln67su4.apps.googleusercontent.com',
    iosBundleId: 'com.example.csaQuizApp',
  );
}
